const savedMovies = [{
  id: 3,
  nameRU: ' Без обратного пути',
  nameEN: 'No Distance Left to Run',
  director: 'Уилл Лавлейс, Дилан Сотерн',
  country: 'Великобритания',
  year: '2010',
  duration: 104,
  description: 'Затеянный по такому подозрительному поводу, как реюнион Blur в 2009-м году фильм начисто лишен присущего моменту пафоса и выхолощенности речей. Вернее, что-то похожее неизбежно возникает, когда ты видишь, как забитый до отказа Гайд-парк как в последний раз ревет «Song 2», но это лишь буквальное свидетельство того, что Blur — великая группа. К счастью, помимо прямых и косвенных свидетельств этого, в «No Distance Left to Run» хватает острых углов, неловких моментов и всего того сора, из которого рождаются по-настоящему отличные группы: помимо важных, но общеизвестных моментов (вроде соперничества с Oasis за первенство в том же бритпопе) визуализируются и те, что всегда оставались за кадром: наркотическая зависимость, неутихающие костры амбиций, ревность, обиды, слава — и все это блестяще снято на фоне истории того, что вообще происходило в Британии времен Блэра.',
  trailerLink: 'https://www.youtube.com/watch?v=6iYxdghpJZY',
  created_at: '2020-11-23T14:17:23.257Z',
  updated_at: '2020-11-23T14:17:23.257Z',
  image: {
    id: 3,
    name: 'blur',
    alternativeText: '',
    caption: '',
    width: 460,
    height: 298,
    formats: {
      thumbnail: {
        hash: 'thumbnail_blur_a43fcf463d',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 241,
        height: 156,
        size: 8.32,
        path: null,
        url: '/uploads/thumbnail_blur_a43fcf463d.jpeg',
      },
    },
    hash: 'blur_a43fcf463d',
    ext: '.jpeg',
    mime: 'image/jpeg',
    size: 21.07,
    url: '/uploads/blur_a43fcf463d.jpeg',
    previewUrl: null,
    provider: 'local',
    provider_metadata: null,
    created_at: '2020-11-23T14:17:01.702Z',
    updated_at: '2020-11-23T14:17:01.702Z',
  },
},  {
  id: 10,
  nameRU: ' Hit So Hard: Школа жизни Патти Шемель',
  nameEN: 'Hit So Hard: The Life & Near Death Story of Patty Schemel',
  director: 'П.Дэвид Эберсол',
  country: 'США',
  year: '2011',
  duration: 103,
  description: 'Это история о тех, кто выжил в 90-е, рассказанная от первого лица: Патти Шемель, барабанщица «золотого» состава группы Hole, открытая лесбиянка и подруга Курта Кобейна, сняла более сорока часов видео на 8-миллиметровую пленку еще в самом начале девяностых. Кобейн, держащий на руках дочь, Кортни Лав, бренчащая что-то на гитаре, сама Патти, зачитывающая в слух итоговой номер Rolling Stone за 94-й год — все это легло в основу Hit So Hard, в котором Дэвид Эбесол реконструирует историю всего беспробудного, безнадежного и до сих пор притягательного поколения 90-х',
  trailerLink: 'https://www.youtube.com/watch?v=DMvFMeaGj_w',
  created_at: '2020-12-02T21:02:28.791Z',
  updated_at: '2020-12-02T21:02:28.791Z',
  image: {
    id: 10,
    name: 'images',
    alternativeText: '',
    caption: '',
    width: 300,
    height: 168,
    formats: {
      thumbnail: {
        hash: 'thumbnail_images_244e1fd56f',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 245,
        height: 137,
        size: 11.76,
        path: null,
        url: '/uploads/thumbnail_images_244e1fd56f.jpeg',
      },
    },
    hash: 'images_244e1fd56f',
    ext: '.jpeg',
    mime: 'image/jpeg',
    size: 14.8,
    url: '/uploads/images_244e1fd56f.jpeg',
    previewUrl: null,
    provider: 'local',
    provider_metadata: null,
    created_at: '2020-12-02T21:01:43.016Z',
    updated_at: '2020-12-02T21:01:43.016Z',
  },
},  {
  id: 15,
  nameRU: 'Сепарадо!',
  nameEN: 'Separado!',
  director: 'Дилан Гош, Графф Рис',
  country: 'Великобритания',
  year: '2010',
  duration: 84,
  description: 'Графф Рис, вокалист психоделической британской группы Super Furry Animals, отправляется в Патагонию, чтобы найти своего дальнего, таинственно исчезнувшего родственника, тоже музыканта. В процессе поисков он охотно прибегает к магическим свойствам шлема Пауэр Рейнджера, путешествует на крыше своего автомобиля и устраивает концерты в чистом поле для диких лошадей. Отчасти документальный фильм, отчасти остроумная выдумка, по жанру более всего напоминающая роуд-муви, «Сепарадо!» – это, прежде всего, история о том, что собственные корни иногда следует искать в собственном же воображении. Что, конечно, не мешает Рису колесить по Южной Америке, знакомиться, кажется, со всеми примечательными местными жителями на своем пути и походя устраивать увлекательнейший ликбез не только по лоу-фай электронике, но и по местной истории.',
  trailerLink: 'https://www.youtube.com/watch?v=r2IfD-6iS3Y',
  created_at: '2020-12-02T21:14:58.142Z',
  updated_at: '2020-12-02T21:14:58.142Z',
  image: {
    id: 15,
    name: 'загруженное',
    alternativeText: '',
    caption: '',
    width: 259,
    height: 194,
    formats: {
      thumbnail: {
        hash: 'thumbnail_zagruzhennoe_cba9c9f900',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 208,
        height: 156,
        size: 11.75,
        path: null,
        url: '/uploads/thumbnail_zagruzhennoe_cba9c9f900.jpeg',
      },
    },
    hash: 'zagruzhennoe_cba9c9f900',
    ext: '.jpeg',
    mime: 'image/jpeg',
    size: 16.4,
    url: '/uploads/zagruzhennoe_cba9c9f900.jpeg',
    previewUrl: null,
    provider: 'local',
    provider_metadata: null,
    created_at: '2020-12-02T21:14:13.176Z',
    updated_at: '2020-12-02T21:14:13.176Z',
  },
}];

export {savedMovies};
